/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _P1_H_RPCGEN
#define _P1_H_RPCGEN

#include <rpc/rpc.h>
/* add header file */
#include <pthread.h>
#include <unistd.h> 

#ifdef __cplusplus
extern "C" {
#endif


#define P_PROG 0x31111100
#define P_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define get_time 1
extern  int * get_time_1(void *, CLIENT *);
extern  int * get_time_1_svc(void *, struct svc_req *);
#define delay 2
extern  int * delay_1(int *, CLIENT *);
extern  int * delay_1_svc(int *, struct svc_req *);
extern int p_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define get_time 1
extern  int * get_time_1();
extern  int * get_time_1_svc();
#define delay 2
extern  int * delay_1();
extern  int * delay_1_svc();
extern int p_prog_1_freeresult ();
#endif /* K&R C */
int tod;
#ifdef __cplusplus
}
#endif

#endif /* !_P1_H_RPCGEN */
