/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "p1.h"


void
p_prog_1(char *host)
{
	CLIENT *clnt;
	int  *result_1;
	char *get_time_1_arg;
	int  *result_2;
	int  delay_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, P_PROG, P_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = get_time_1((void*)&get_time_1_arg, clnt);
	if (result_1 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_2 = delay_1(&delay_1_arg, clnt);
	if (result_2 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	CLIENT *clnt;
	int option, interval;
	int *elapse_time, *delay_time;
	char *arg;
	clnt = clnt_create(argv[1], P_PROG, P_VERS,"tcp");

	while(1){
		printf("Input option(1: get_time(), 2: delay(), 3: exit the client)\n");
		scanf("%d",&option);

		if(option == 1){
			elapse_time = get_time_1((void*)&arg, clnt);
			printf("Elapsed seconds form the beginning %d(sec)\n",*(elapse_time));
		}
		else if(option == 2){
			printf("Input the interval time ");
			scanf("%d", &interval);
			delay_time = delay_1(&interval, clnt);
			printf("Present time after delay %d(sec)\n",*(delay_time));
		}
		else{
			break;
		}
	}
	exit (0);
}
