/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "p1.h"

int *
get_time_1_svc(void *argp, struct svc_req *rqstp)
{
	static int  result;

	result = tod;

	return &result;
}

int *
delay_1_svc(int *argp, struct svc_req *rqstp)
{
	static int  result;
	int delay_time;

	delay_time = *argp;

	printf("Present time is %d(sec)\n",tod);
	sleep(delay_time);
	result= tod;

	return &result;
}
